spring.application.name=fitness-api

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:fitness}
spring.datasource.username=${POSTGRES_USER:fitness}
spring.datasource.password=${POSTGRES_PASSWORD:fitness_dev}

spring.jpa.hibernate.ddl-auto=none